# Generated by Django 4.0.3 on 2022-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancle', 'Cancle')], default='pending', max_length=50),
        ),
    ]
