# Generated by Django 4.0.3 on 2022-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_cart_quantity_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[('mobile', 'mobile'), ('camera', 'camera'), ('tshirt', 'tshirt'), ('headphone', 'headphone')], max_length=100),
        ),
    ]
