# Generated by Django 4.0.3 on 2022-03-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[('M', 'mobile'), ('C', 'camera'), ('T', 'tshirt'), ('HP', 'headphone')], max_length=2),
        ),
    ]
