# Generated by Django 4.0.3 on 2022-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_customer_provience_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Huwai', 'Huwai')], max_length=20),
        ),
    ]
