# Generated by Django 4.0.3 on 2022-03-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cart_quantity_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
